name: Pod-WikiText
version: 0.08
version_from: lib/Pod/WikiText.pm
installdirs: site
requires:
  Test::Harness: 0
  Test::More: 0
  File::Spec: 0
  Text::Wrap: 0
  Text::Tiki: 0
  Syntax::Highlight::Engine::Kate: 0
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.38
